version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    timezone: Europe/Copenhagen
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    timezone: Europe/Copenhagen
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Copenhagen
