on: push
name: Docker build and push

permissions:
  actions: read
  contents: write
  packages: write
  pull-requests: read
  security-events: write

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Bump version and push tag
      if: github.ref == 'refs/heads/main'
      uses: anothrNick/github-tag-action@master
      id: version
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: true
        DEFAULT_BUMP: patch
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to DockerHub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx.outputs.name }}
        load: ${{ github.ref != 'refs/heads/main' }}
        context: .
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ steps.version.outputs.tag || github.sha }}
          org.opencontainers.image.revision=${{ github.sha }}
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.version.outputs.tag || github.sha }}
        push: ${{ github.ref == 'refs/heads/main' }}
    - name: Anchore Container Vulnerability Scan
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.tag || github.sha }}
        acs-report-enable: true
    - name: Upload Anchore Container Vulnerability Scan SARIF report
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
